# Generated by Django 4.1.7 on 2023-06-02 09:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogApp', '0008_remove_postcomments_title_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComments',
            new_name='PostComment',
        ),
    ]
