# Generated by Django 4.1.7 on 2023-06-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0009_rename_postcomments_postcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='last_name',
        ),
    ]
