# Generated by Django 4.1.7 on 2023-06-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0012_alter_userinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='blockedUsers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
