# Generated by Django 4.1.7 on 2023-06-02 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0014_blogpost_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='files',
            new_name='file',
        ),
    ]
